In [1]:
import numpy as np

<h3><b>ARRAY OPERATIONS</b></h3>

*Arithmatic operations*

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,2,3,4,5])

In [7]:
arr2 = a1 + a2 # element-wise addition and have same no of size

In [9]:
arr3 = a1 - a2
arr4 = a1 * a2
arr5 = a1 / a2  
arr6 = a1 % a2
arr7 = a1 ** a2
arr8 = a1 // a2
arr2, arr3, arr4, arr5, arr6, arr7, arr8

(array([ 2,  4,  6,  8, 10]),
 array([0, 0, 0, 0, 0]),
 array([ 1,  4,  9, 16, 25]),
 array([1., 1., 1., 1., 1.]),
 array([0, 0, 0, 0, 0]),
 array([   1,    4,   27,  256, 3125]),
 array([1, 1, 1, 1, 1]))

<i>Broadcasting</i>

In [11]:
l = [1,2,3,4,5]
arr = np.array(l)
arr+10

array([11, 12, 13, 14, 15])


<i>Deep and Shallow copy</i>

In [12]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice = slice *10
slice  # slice will take different memory location


array([10, 20, 30, 40, 50])

In [ ]:
a # original array remains unchanged -- shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
#deep copy 
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
b[0] = 13
b

array([13,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a

array([13,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

<i>Matrix Operation</i>

In [22]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
B

array([[5, 6],
       [7, 8]])

In [25]:
A@B  # matrix multiplication

array([[19, 22],
       [43, 50]])

In [26]:
np.dot(A,B) # matrix multiplication

array([[19, 22],
       [43, 50]])

In [27]:
A.T # transpose of matrix A

array([[1, 3],
       [2, 4]])

<h3><b>🧮 Advance Array Manipulation</b></h3>

<i>Stacking Array</i>

In [28]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [29]:
np.vstack((a,b))  # vertical stacking  

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
np.hstack((a,b))  # horizontal stacking

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
np.column_stack((a,b))  # column stacking

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

<i>Splitting Array</i>

In [34]:
c = np.arange(1,17 ).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
np.hsplit(c,2)  # horizontal splitting into 2 arrays

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [37]:
np.hsplit(c,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [38]:
np.vsplit(c,2) # vertical splitting into 2 arrays

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]