In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [3]:
arr = np.arange(1,30,3)  # start, stop, step
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [ ]:
arr[4]  # access element at index 4


array([ 4,  7, 10, 13])

In [ ]:
arr[1:5] # slicing from index 1 to 4

array([ 4,  7, 10, 13])

In [7]:
arr[::2]  # slicing with step size 2

array([ 1,  7, 13, 19, 25])

In [ ]:
arr[3:] # from index 3 to end

array([10, 13, 16, 19, 22, 25, 28])

NUMPY INDEXING AND SLICING OF MATRIX

In [9]:
arr = np.arange(1,31).reshape(6,5)  # 6 rows and 5 columns
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[2] # access third row

array([11, 12, 13, 14, 15])

In [11]:
arr[0,0]  # first row, first column

np.int64(1)

In [ ]:
arr[4,3] # fifth row, fourth column

np.int64(24)

In [13]:
arr[0:2, 1:4]  # first two rows, columns 1 to 3

array([[2, 3, 4],
       [7, 8, 9]])

In [15]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,3]    # all rows, fourth column

array([ 4,  9, 14, 19, 24, 29])

BOOLEAN INDEXING

In [18]:
ar = np.arange(11,21)
ar

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
bool_index = ar%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
ar = ar[bool_index]
ar

array([12, 14, 16, 18, 20])