In [1]:
import numpy as np

Basic Array Creation

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a = [1,2,3.4,'hello']
b = np.array(a)
b

array(['1', '2', '3.4', 'hello'], dtype='<U32')

In [6]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function


In [9]:
a = np.arange(0, 10)
b = np.arange(0,10,2)
a, b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 2, 4, 6, 8]))

In [10]:
a = np.zeros((3,4)) # 3 rows and 4 columns
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
arr = np.ones((2,3,4)) # 2 blocks, 3 rows and 4 columns
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
arr = np.ones((3,4)) # 3 rows and 4 columns
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(0, 10, 5) # 5 values between 0 and 10 having equal spacing
arr


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Random Generation Function

In [17]:
np.random.rand(10)

array([0.84705885, 0.21343665, 0.09610867, 0.9399488 , 0.09212452,
       0.34825658, 0.04571132, 0.37086935, 0.38666001, 0.70236801])

In [18]:
np.random.randn(10)

array([-1.1815039 , -0.49088473, -1.38847458, -1.9434722 , -0.61664014,
        1.35196806, -0.8865071 , -1.1759186 ,  0.1244069 , -2.78061661])

In [19]:
np.random.randint(0, 100, 10 ) # 10 random integers between 0 and 100

array([ 8, 49, 95, 90, 42, 47, 27, 52, 99, 73], dtype=int32)

Array Attributes

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.shape

(3, 3)

In [24]:
arr.size

9

In [25]:
arr.dtype

dtype('int64')

Array Methods

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.max()


np.int64(9)

In [30]:
arr.min()

np.int64(1)

In [35]:
arr.sum()

np.int64(45)

In [37]:
np.sum(arr, axis=0)  # column-wise sum

array([12, 15, 18])

In [38]:
arr.mean()

np.float64(5.0)

In [39]:
arr.std()  # standard deviation

np.float64(2.581988897471611)

In [40]:
arr.argmax()  # index of maximum value

np.int64(8)

In [41]:
arr.argmin()  # index of minimum value

np.int64(0)

Reshaping and Resizing

In [43]:
ar = np.arange(1, 31)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [47]:
ar = ar.reshape(6,5)  # 6 rows and 5 columns
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])